coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 90%
        threshold: 5%
    patch:
      default:
        target: 90%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "tests/"
  - "docs/"
  - "setup.py"
  - "conftest.py"
  - "*.pyc"
  - "__pycache__"
