[tool.poetry]
name = "git-camus"
version = "0.1.0"
description = "Craft Git Commit Messages with Existential Flair"
authors = ["Evgeny Rachlenko <evgeny.rachlenko@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
click = "^8.1.8"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
ruff = "^0.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

#run git-camus
[ tool.poetry.scripts ]
git-camus = "git_camus:main"
pytest = "pytest:main"

