"""Configuration file for the Sphinx documentation builder."""

import os
import sys

# Add the project root directory to the path so Sphinx can find the modules
sys.path.insert(0, os.path.abspath("../.."))

# -- Project information -----------------------------------------------------
project = "Git-Camus"
copyright = "2024, Evgeny Rachlenko"
author = "Evgeny Rachlenko"

# The full version, including alpha/beta/rc tags
release = "0.2.0"

# -- General configuration ---------------------------------------------------
extensions = [
    "sphinx.ext.autodoc",  # Include documentation from docstrings
    "sphinx.ext.viewcode",  # Add links to the source code
    "sphinx.ext.napoleon",  # Support for Google and NumPy style docstrings
    "sphinx.ext.intersphinx",  # Link to other projects' documentation
    "myst_parser",  # Support for Markdown files
]

# Add any paths that contain templates here, relative to this directory
templates_path = ["_templates"]

# The suffix of source filenames
source_suffix = {".rst": "restructuredtext", ".md": "markdown"}

# The master toctree document
master_doc = "index"

# The language for content autogenerated by Sphinx
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use
pygments_style = "sphinx"

# -- Options for HTML output -------------------------------------------------
html_theme = "sphinx_rtd_theme"

# Theme options are theme-specific and customize the look and feel of a theme
html_theme_options = {
    "navigation_depth": 4,
    "titles_only": False,
    "collapse_navigation": False,
    "sticky_navigation": True,
    "includehidden": True,
    "logo_only": False,
    "display_version": True,
}

# Add any paths that contain custom static files
html_static_path = ["_static"]

# Output file base name for HTML help builder
htmlhelp_basename = "Git-Camusdoc"

# -- Options for LaTeX output ------------------------------------------------
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper')
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt')
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble
    # 'preamble': '',
    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files
latex_documents = [
    (master_doc, "Git-Camus.tex", "Git-Camus Documentation", "Evgeny Rachlenko", "manual")
]

# -- Options for manual page output ------------------------------------------
# One entry per manual page
man_pages = [(master_doc, "git-camus", "Git-Camus Documentation", [author], 1)]

# -- Options for Texinfo output ----------------------------------------------
# Grouping the document tree into Texinfo files
texinfo_documents = [
    (
        master_doc,
        "Git-Camus",
        "Git-Camus Documentation",
        author,
        "Git-Camus",
        "Craft Git commit messages with existential flair using local Ollama.",
        "Miscellaneous",
    )
]

# -- Options for Epub output -------------------------------------------------
# Bibliographic Dublin Core info
epub_title = project

# A unique identification for the text
# epub_uid = ''

# A list of files that should not be packed into the epub file
epub_exclude_files = ["search.html"]

# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------
# Example configuration for intersphinx: refer to the Python standard library
intersphinx_mapping = {"https://docs.python.org/": None}

# -- Options for autodoc extension -------------------------------------------
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
}

# -- Options for Napoleon extension ------------------------------------------
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True
