# Default values for git-camus
replicaCount: 1

image:
  repository: ghcr.io/rachlenko/git-camus
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: git-camus.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Git Camus specific configuration
gitCamus:
  config:
    ollama:
      host: "http://ollama:11434"
      model: "llama3.2"
    run:
      prompt_message: |
        You are an AI assistant that generates philosophical commit messages in the style of Albert Camus.
        Your task is to analyze git changes and create a commit message that reflects on the absurdity, rebellion, and human condition.

        Git Diff:
        {diff}

        Git Status:
        {status}

        Generate a philosophical commit message that:
        1. Reflects on the nature of the changes made
        2. Incorporates themes of existentialism and the absurd
        3. Is concise but meaningful (max 150 characters)
        4. Avoids technical jargon in favor of philosophical reflection

        Respond with only the commit message, no explanations or additional text.

# Ollama dependency configuration
ollama:
  enabled: true
  service:
    type: ClusterIP
    port: 11434
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""