# Development values for git-camus
replicaCount: 1

image:
  repository: git-camus
  pullPolicy: Never
  tag: "dev"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

service:
  type: NodePort
  port: 8000
  nodePort: 30800

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: git-camus-dev.local
      paths:
        - path: /
          pathType: Prefix

gitCamus:
  config:
    ollama:
      host: "http://localhost:11434"
      model: "llama3.2"

ollama:
  enabled: false  # Use external Ollama in development